import { Metadata } from "next";
export const metadata: Metadata = {
  title: {
    default: "Next Page", // for childern who dont have title
    template: "%s | convention", // for the childern
  },
  description: "Generated by Next.js",
};
/*
 *In Next.js, layouts provide a way to organize and reuse consistent parts 
 of your application's UI (like headers, footers, and sidebars) across multiple pages.
  Here’s an overview of how layouts work and how you can implement them in Next.js:
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "navy", height: "40px" }}>
          <p style={{ margin: "10px 10px", padding: "2px", fontSize: "30px" }}>
            Header
          </p>
        </header>

        {children}
        <footer style={{ backgroundColor: "yellow", height: "40px" }}>
          <p style={{ margin: "10px 10px", padding: "2px", fontSize: "30px" }}>
            Footer
          </p>
        </footer>
      </body>
    </html>
  );
}
